const actionTypes = {
  ARTIST: {
    FETCH_REQUEST: 'ARTIST_FETCH_REQUEST',
    FETCH_SUCCESS: 'ARTIST_FETCH_SUCCESS',
    FETCH_FAILURE: 'ARTIST_FETCH_FAILURE',
  },
  ARTISTS: {
    FETCH_REQUEST: '/ARTISTS_FETCH_REQUEST',
    FETCH_SUCCESS: '/ARTISTS_FETCH_SUCCESS',
    FETCH_FAILURE: '/ARTISTS_FETCH_FAILURE',
  }
}

export default actionTypes;
